baseURL: https://zulko.github.io/bricks_and_scissors/
languageCode: en-us
title: Bricks and Scissors
markup:
  goldmark:
    renderer:
      unsafe: true
custom_css: ["assets/custom.css"]
googleAnalytics: UA-194244778-1
theme: "PaperMod"
params:
  ShowReadingTime: true
  disableThemeToggle: true
  homeInfoParams:
    Title: "Bricks and Scissors"
    Content: >

      Blog on the computational side of Synthetic Biology, with a focus on DNA design and manufacturing.
      Mostly drawing from experience with medium- to large-scale bioengineering projects at an academic biofoundry.
      Text and original figures are under a
      <a href="https://creativecommons.org/licenses/by/2.0/"> CC-BY-2.0 license</a>.

      <img style='margin: 1em auto' src='title.svg'/>
  ShowShareButtons: true
  env: production
  # analytics:
  #   google:
  #     SiteVerificationTag: G-1EZWW833S2
  author: Zulko
  outputs:
    home:
      - HTML
      - RSS
      - JSON
  socialIcons:
    - name: github
      url: "https://github.com/Zulko/bricks_and_scissors"
    - name: RsS
      url: "index.xml"
