baseURL: http://example.org/
languageCode: en-us
title: Bricks and Scissors
theme: "PaperMod"
markup:
  goldmark:
    renderer:
      unsafe: true
custom_css: ["assets/custom.css"]
params:
  ShowReadingTime: true
  disableThemeToggle: true
  homeInfoParams:
    Title: "Bricks and Scissors"
    Content: >

      Blog on the computational side of Synthetic Biology, with a focus on DNA design and manufacturing.
      Mostly drawing from experience with medium- to large-scale bioengineering projects at an academic biofoundry.
      Text and original figures are under a
      <a href="https://creativecommons.org/licenses/by/2.0/"> CC-BY-2.0 license</a>.

      <img style='margin: 1em auto' src='title.svg'/>
  ShowShareButtons: true
